run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - misspell
    - gosec

linters-settings:
  gosec:
    excludes:
      - G301
      - G304
      - G305

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
